server:
  port: 9002

spring:
  #默认使用Hikari数据库连接池
  datasource:
    #1.驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    #2.数据库连接的url
    url: jdbc:mysql://localhost:3306/metaverse
    #3.数据库的用户名
    username: root
    #4.数据库的密码
    password: 557902
  redis:
    host: localhost      # Redis 服务器的地址，默认为 localhost
    port: 6379           # Redis 服务器的端口号，默认为 6379
    password:            # Redis 服务器的密码，如果未设置密码，则留空
    database: 0          # 使用的数据库索引，默认为 0，Redis 支持 0 到 15 共 16 个数据库
    timeout: 5000ms      # 连接超时时间，默认为 5000 毫秒
    jedis:
      pool:
        max-active: 8    # 连接池最大连接数，默认为 8
        max-wait: -1ms   # 连接池最大等待时间，默认为 -1 表示无限等待
        max-idle: 8      # 连接池最大空闲连接数，默认为 8
        min-idle: 0      # 连接池最小空闲连接数，默认为 0

#将mybatis输出到控制台
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名法
    map-underscore-to-camel-case: true

#mybatis-plus:
#  type-aliases-package: com.metaverse.user.db.mapper


snowflake:
  datacenterId: 1
  workerId: 1

#spring:
#  mail:
#    # QQ 邮箱服务器地址
#    host: smtp.qq.com
#    # 你的 QQ 邮箱账号
#    username: 315626261@qq.com
#    # QQ 邮箱授权码
#    password: xxfyawvjzqpfbhdj
#    properties:
#      mail:
#        # 邮件编码格式
#        default-encoding: UTF-8
#      smtp:
#        ssl:
#          # 启用 SSL 加密
#          enable: true



metaverse:
  config:
    system-permissions:
      - UPDATE.USER.PERMISSION
      - VIEW.USER.PERMISSION
      - DELETE.USER.PERMISSION
      - DELETE.REGION.PERMISSION