server:
  port: 9002

spring:
  #默认使用Hikari数据库连接池
  datasource:
    #1.驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    #2.数据库连接的url
    url: jdbc:mysql://localhost:3306/demo1
    #3.数据库的用户名
    username: root
    #4.数据库的密码
    password: 557902

#将mybatis输出到控制台
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名法
    map-underscore-to-camel-case: true

snowflake:
  datacenterId: 1
  workerId: 1